name: Trigger Coolify Deployment

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Trigger deployment in Coolify
      - name: Trigger Coolify Deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_BEARER_TOKEN }}" \
            ${{ secrets.COOLIFY_WEBHOOK_URL }}

      # Trigger deployment in Coolify
      - name: Trigger Coolify Deployment for tensen.id
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_BEARER_TOKEN }}" \
            ${{ secrets.COOLIFY_WEBHOOK_URL_TENSEN_ID }}
