name: Test application

on:
  push:
    branches:
      - 'main'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Copy Environment File
        run: cp .env.testing .env

      - name: Composer install
        run: |
          composer install -q --no-interaction --prefer-dist --optimize-autoloader

      - name: Create SQLite Database
        run: touch database/testing.sqlite

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Install Node Dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build Node Dependencies
        run: npm run build

      - name: Tests
        run: composer test
